<?php

namespace ContainerSccNkAC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_MnTIRxOService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.MnTIRxO' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.MnTIRxO'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\CombinadoController::index' => ['privates', '.service_locator.Paw3BkS', 'get_ServiceLocator_Paw3BkSService', true],
            'App\\Controller\\PrediccionesController::index' => ['privates', '.service_locator.vPqplXS', 'get_ServiceLocator_VPqplXSService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Controller\\CombinadoController:index' => ['privates', '.service_locator.Paw3BkS', 'get_ServiceLocator_Paw3BkSService', true],
            'App\\Controller\\PrediccionesController:index' => ['privates', '.service_locator.vPqplXS', 'get_ServiceLocator_VPqplXSService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
        ], [
            'App\\Controller\\CombinadoController::index' => '?',
            'App\\Controller\\PrediccionesController::index' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\CombinadoController:index' => '?',
            'App\\Controller\\PrediccionesController:index' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
