<?php

namespace ContainerE8tgqHy;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Paw3BkSService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Paw3BkS' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Paw3BkS'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'combinadoRepository' => ['privates', 'App\\Repository\\CombinadoRepository', 'getCombinadoRepositoryService', true],
        ], [
            'combinadoRepository' => 'App\\Repository\\CombinadoRepository',
        ]);
    }
}
